name: Security Scans

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Bandit
      run: pip install bandit

    - name: Bandit Scan
      run: bandit -ii -ll -r . -f json -o bandit-report.json

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: bandit_findings
        path: bandit-report.json

  image_scan:
    name: Build Image and Run Image scan
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Docker
      uses: docker-practice/actions-setup-docker@v1
      with:
        docker_version: '20.10.7'

    - name: Build Docker image
      run: docker build -f Dockerfile -t myapp:latest .

    - name: Install Docker Scout
      run: |
        curl -fsSL https://raw.githubusercontent.com/docker/scout-cli/main/install.sh -o install-scout.sh
        sh install-scout.sh

        echo ${{ secrets.REPO_PWD }} | docker login -u ${ secrets.REPO_USER }} --password-stdin

    - name: Docker Scout Scan
      run: |
        docker scout quickview myapp:latest
        docker scout cves myapp:latest
